### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by j08lue** [oarcher/sentinelrequest#1]
I know this package was just published. But might be good to already add the right license, if you are making it open source. 😄 

https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by oarcher** [comment]
Ok, I've opted for the 'MIT' license  in b7823e861f684974e8
